export const Products = [
  { name: "Siomay", description: "Dikukus dan disajikan dengan bumbu kacang gurih dan pedas." },
  { name: "Batagor", description: "Bakso tahu goreng dengan saus kacang yang menggoda selera makan." },
  { name: "Pempek", description: "Ikan giling bercampur tepung, disajikan dengan kuah cuka khas Palembang." },
  { name: "Gorengan", description: "Camilan murah meriah seperti tempe, tahu, dan pisang goreng renyah." },
  { name: "Cilok", description: "Aci bulat kenyal yang direbus dan disiram saus kacang pedas." },
  { name: "Cireng", description: "Aci goreng dengan tekstur renyah di luar, kenyal di dalam." },
  { name: "Bakso", description: "Bola daging sapi kenyal dalam kuah kaldu gurih dan hangat." },
  { name: "Sate Ayam", description: "Daging ayam ditusuk dan dibakar, disiram saus kacang manis." },
  { name: "Sate Taichan", description: "Sate ayam tanpa bumbu kacang, disajikan dengan sambal pedas." },
  { name: "Mie Ayam", description: "Mie kenyal dengan topping ayam manis gurih dan sayuran segar." },
  { name: "Nasi Goreng", description: "Nasi yang digoreng dengan bumbu khas, telur, dan kerupuk." },
  { name: "Kwetiau Goreng", description: "Mie pipih goreng dengan campuran daging, sayur, dan kecap." },
  { name: "Bubur Ayam", description: "Bubur nasi lembut dengan suwiran ayam dan kerupuk gurih." },
  { name: "Lontong Sayur", description: "Lontong dengan kuah santan sayur labu dan sambal pedas." },
  { name: "Ketoprak", description: "Tahu, bihun, dan lontong disiram saus kacang dan kecap manis." },
  { name: "Gado-Gado", description: "Sayuran rebus dengan bumbu kacang dan kerupuk sebagai pelengkap." },
  { name: "Tahu Gejrot", description: "Tahu goreng disiram kuah pedas manis dengan bawang dan cabai." },
  { name: "Tahu Bulat", description: "Tahu digoreng bulat dan dijual hangat dari mobil pick-up." },
  { name: "Martabak Manis", description: "Adonan tebal berisi coklat, keju, dan kacang, sangat legit." },
  { name: "Martabak Telur", description: "Kulit tipis berisi telur dan daging, digoreng hingga renyah." },
  { name: "Roti Bakar", description: "Roti panggang dengan isian coklat, keju, atau selai kacang." },
  { name: "Es Doger", description: "Minuman dingin dengan tape, kelapa, dan susu kental manis." },
  { name: "Es Cendol", description: "Minuman santan dengan cendol hijau dan gula merah cair." },
  { name: "Es Pisang Ijo", description: "Pisang dibalut adonan hijau, disajikan dengan sirup dan susu." },
  { name: "Es Teler", description: "Campuran alpukat, kelapa, nangka, dan susu dalam es serut." },
  { name: "Jus Buah Segar", description: "Minuman sehat dari buah asli, segar dan penuh vitamin." },
  { name: "Kue Cubit", description: "Kue kecil manis yang mekar saat dipanggang, sering diberi topping." },
  { name: "Kue Pukis", description: "Kue lembut dengan rasa manis, sering dijual di pinggir jalan." },
  { name: "Kue Pancong", description: "Kue kelapa panggang dengan rasa gurih dan tekstur renyah." },
  { name: "Pisang Goreng", description: "Pisang matang digoreng dengan tepung, cocok untuk camilan sore." },
  { name: "Singkong Keju", description: "Singkong goreng yang empuk, ditaburi keju parut dan susu." },
  { name: "Seblak", description: "Kerupuk basah dimasak pedas dengan telur, bakso, dan sayuran." },
  { name: "Bakso Bakar", description: "Bakso ditusuk dan dibakar dengan bumbu manis pedas menggoda." },
  { name: "Sosis Bakar", description: "Sosis besar dibakar dan dilumuri saus barbeque atau sambal." },
  { name: "Telur Gulung", description: "Telur digoreng dan digulung di tusuk sate, favorit anak sekolah." },
  { name: "Burger Lokal", description: "Roti isi daging, sayur, dan saus lokal dengan cita rasa khas." },
  { name: "Hotdog Jalanan", description: "Roti panjang berisi sosis dan saus, dijual di gerobak keliling." },
  { name: "Nasi Uduk", description: "Nasi gurih dengan lauk lengkap seperti ayam goreng dan sambal." },
  { name: "Nasi Kuning", description: "Nasi berbumbu kunyit dengan lauk khas dan kerupuk warna-warni." },
  { name: "Ayam Geprek", description: "Ayam goreng tepung yang digeprek dengan sambal super pedas." }
] as const;


export const randomImage = [
  'https://i0.wp.com/geologyscience.com/wp-content/uploads/2023/04/2006385-1646750776-nickel-2.jpg?resize=600%2C576&ssl=1',
  'https://tse1.mm.bing.net/th/id/OIP.XloUeR5L9YpD3PXOO8bfCwHaDt?',
  'https://tse2.mm.bing.net/th/id/OIP.j6_UyyQ9UiJYrS0Zfy17PwHaFj?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3'
] as const;